FROM progrium/busybox

WORKDIR /usr/src/app
COPY lib64 /usr/lib64
RUN ln -s /usr/lib64/libstdc++.so.6.0.20 /usr/lib64/libstdc++.so.6
COPY wt /usr/bin/wt

EXPOSE 12345

VOLUME "/data"
WORKDIR /data

CMD wt -http -httppath=$HOST -p /data -d /data/img -b /data/build -gen /data/build/img
