FROM gliderlabs/alpine:latest

WORKDIR /usr/src/app
COPY lib64 /usr/lib

COPY wt /usr/bin/wt
RUN chmod +x /usr/bin/wt

EXPOSE 12345

VOLUME "/data"
WORKDIR /data

CMD wt -http -httppath=$HOST -p /data -d /data/img -b /data/build -gen /data/build/img
