FROM gliderlabs/alpine:latest

WORKDIR /usr/src/app
COPY lib64 /usr/lib

COPY wt /usr/bin/wt
RUN chmod +x /usr/bin/wt

EXPOSE 12345

VOLUME "/data"
WORKDIR /data

CMD wt serve -p /data --images-dir /data/img -b /data/build --gen /data/build/img
